version: '3.8'

services:
  web:
    build: .
    ports:
      - "60000:60000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/testdb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REPO_NAME=web
    depends_on:
      - redis
      - db
  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/testdb
      - REDIS_URL=redis://redis:6379/0
      - REPO_NAME=worker
    depends_on:
      - web
      - redis
      - db
  beat:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/testdb
      - REDIS_URL=redis://redis:6379/0
      - REPO_NAME=beat
    depends_on:
      - web
      - redis
      - db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

#volumes:
#  pgdata:
