version: '3.8'

services:
  web:
    build: .
    ports:
      - "60000:60000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/testdb
      - REPO_NAME=web
      - REDIS_HOST=redis
      - REDIS_USE_SSL=True
      - REDIS_PASSWORD=YourPassword
      - REDIS_PORT=6380
    depends_on:
      - redis
      - db
  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/testdb
      - REDIS_HOST=redis
      - REPO_NAME=worker
      - REDIS_USE_SSL=True
      - REDIS_PASSWORD=YourPassword
      - REDIS_PORT=6380
    depends_on:
      - web
      - redis
      - db
#  beat:
#    build: .
#    environment:
#      - DATABASE_URL=postgresql://postgres:password@db:5432/testdb
#      - REDIS_URL=redis://redis:6379/0
#      - REPO_NAME=beat
#    depends_on:
#      - web
#      - redis
#      - db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Non-SSL port
      - "6380:6380"  # SSL port
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./certs:/usr/local/etc/redis/
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

#volumes:
#  pgdata:
