name: Parameter Check

on:
  push:
    paths:
      - 'base_dash_app/application/app_descriptor.py'
      - 'README.md'
  pull_request:
    paths:
      - 'base_dash_app/application/app_descriptor.py'
      - 'README.md'

jobs:
  check-params:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install regex
    - name: Check Parameters
      run: python .github/scripts/param_check.py
