name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build wheel
        run: python setup.py sdist bdist_wheel

      - name: Get the version from setup.py
        id: get_version
        run: |
          echo "::set-output name=VERSION::$(python setup.py --version)"

      - name: Fetch latest release version from GitHub
        id: fetch_latest_release
        run: |
          LATEST_RELEASE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
                            jq -r .tag_name)
          echo "::set-output name=LATEST_RELEASE_VERSION::${LATEST_RELEASE}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release and Upload Wheel
        if: steps.get_version.outputs.VERSION != steps.fetch_latest_release.outputs.LATEST_RELEASE_VERSION
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} dist/* --title "Release ${{ steps.get_version.outputs.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}